name: Publish

on:
    push:
        tags:
            - '*'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Publish to Crates.io
              run: |-
                  cargo login ${{ secrets.CRATES_IO_TOKEN }}
                  cargo publish
